export enum FileType {
  JPEG = 'image/jpeg',
  PNG = 'image/png',
  JPG = 'image/jpg',
  GIF = 'image/gif',
  JFIF = 'application/octet-stream',
  PDF = 'application/pdf',
  DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  DOC = 'application/msword',
  ZIP = 'application/zip',
  MP4 = 'audio/mp4',
  MP3 = 'audio/mpeg',
  OGG = 'audio/ogg',
  AAC = 'audio/aac',
  HTML = 'text/html',
  JS = 'text/javascript',
  TXT = 'text/plain',
  MD = 'text/markdown',
  V_MP4 = 'video/mp4',
  MPV = 'video/MPV',
  AV1 = 'video/AV1',
}
